### ISSUE TITLE
Issue when trying to load a list of struct from a yaml file.

### ISSUE THREAD

**Issue by YassineE** [heetch/confita#47]
Given this type:
```go
type migrationSettings struct {
	Source      string `config:"source,required"`
	Destination string `config:"destination,required"`
	Partitions  int    `config:"partitions,required"`
}
```

The following yaml: 
```yaml
- source: topic1
  destination: topic2
  partitions: 3

- source: topic1
  destination: topic2
  partitions: 3

- source: topic1
  destination: topic2
  partitions: 3
```

The snippet:
```go
var s []migrationSettings

l := confita.NewLoader(file.NewBackend("config.yaml"))
l.Load(context.Background(), &s)

fmt.Println(s)
```

The output:
```shell
[]
```
